set windows-shell := ['pwsh', '-Command']

default:
  @just --list

# Create a new resume starting with the generic CV as a template
new NAME:
  cp cv.docx '{{ NAME }}'

# Clean up temporary files generated by Microsoft Word
clean:
  rm -f "~$"*.docx
